### ISSUE TITLE
doesn't load objects using relative paths like ./objectname

### ISSUE THREAD

**Issue by sebshader** [agraef/pd-lua#10]
when creating an object I can't use ./myobject, like I can for abstractions and externals

**Comment by porres** [comment]
trying to debug this.

say I have the [hello] object in a /pdlua subfolder. We need [declare -path pdlua] otherwise it won't work. If you just try [hello], it won't work, because it is in the subfolder, but if you try to call it as [padlua/hello], it fails as well. Now, here's the weird part, if I try to create it again as [hello], it finds it! If I try [pdlua/hello] again, it doesn't work again.

This indicates that the object is found by Pd when trying the '/pdlua' prefix and it is remembered when trying just [hello].

Anyway, there's a clear bug here we should try and fix. By using the debug functions in the object I get:

pdlua_new: s->s_name is pdlua/hello
pdlua_new: start with stack top 0
pdlua_pushatomtable: stack top 3
pdlua_pushatomtable: end. stack top 4
pdlua_new: before lua_pcall(L, 2, 1, 0) stack top 4
pdlua_new: done lua_pcall(L, 2, 1, 0) stack top 2
**pdlua_new: done FALSE lua_islightuserdata(L, -1)**

This means it fails here where it should be TRUE --> https://github.com/agraef/pd-lua/blob/master/pdlua.c#L466

**Comment by porres** [comment]
if we check pd's console with "verbose" checked in preferences/path, we can see that Pd does find 'pdlua/hello' easily. It just can't load it.

![Screen Shot 2023-01-08 at 02 14 53](https://user-images.githubusercontent.com/5360142/211181627-57af61ff-c15b-4886-bcf3-9568c2e7aab4.png)

**Comment by porres** [comment]
note we even get it to print 'hello universe'

**Comment by porres** [comment]
hmmm, I see where it fails now. Pd loads the file alright and 'hello universe' is printed... the fail happens inside the hello.pd_lua file right next, in 

local Hello = pd.Class:new():register("hello")

If I change it to 

local Hello = pd.Class:new():register("pdlua/hello")

then it works when I create the object as [pdlua/hello].

**Comment by agraef** [comment]
Should be fixed now. Please test, thanks.

**Comment by sebshader** [comment]
seems like it isn't working here quite the same.. if I do [../luaobj] in some subdirectory it doesn't create

**Comment by agraef** [comment]
Lua 5.1 is very old, I'm surprised that the current version of pd-lua works with that at all. (5.2 might still work, but 5.3+ is what I'd recommend.)

That said, I'm having issues with `..` as well. Sometimes it works, sometimes it fails with this mysterious message:

~~~
maximum object loading depth 1000 reached
../pdlua/hello
... couldn't create
~~~

Looks like the vanilla loader is getting confused by the initial `..` and recurses. I'm not sure whether pd-lua is to blame here, or the loader. Will have to look into it.

**Comment by sebshader** [comment]
well like I said, it works for binary externals and abstractions so it seems like there is something pdlua could do..
I like to use 5.1 both because of JIT and because ```setfenv``` and ```getfenv``` allow a more efficient/less hacky implementation of dynamic variables to make music with, so you could have one function use the parent's scale or tempo or something. (don't have to iterate to get the ```_ENV``` upvalues of a function using the debug library).

anyways, would it make sense to re-open until a solution is found?

**Comment by agraef** [comment]
Yes, I'm reopening because my implementation isn't really working in some corner cases.

The actual issue is that a pd_lua file registers its class name by itself, and this is just the basename, without any path. So, you can't just load, say, ./hello.pd_lua and ../hello.pd_lua both implementing the same hello class. With Pd abstractions this kind of thing works, but it's basically impossible with the way pd-lua is currently designed.

The situation is really similar to what happens if you have two external binary objects with the same name under two different paths. Pd will then print a warning and just load one of the instances. At least that's how I remember it.

So the pdlua loader should do something similar. To do that, on the C side I need to check if a class with the same basename has already been registered on the Lua side, in which case it should print a warning and just instantiate the existing Lua object class instead.

**Comment by sebshader** [comment]
@agraef I believe w/ pd it is possible to load different binaries by path. e.g. if I use ```[lib1/classname]``` and ```[lib2/classname]``` it will result in 2 different classes.

**Comment by agraef** [comment]
> in which case it should print a warning and just instantiate the existing Lua object class instead.

Unfortunately, this doesn't work either. The loader is a harsh mistress. :( It's either create a new class, or bail out with failure. Everything else leaves the loader in an unstable state in which it recurses and crashes.

Oh well, then so be it. I can still check for class name collisions and bail out with a sensible error message. that will at least fix that ominous "maximum object loading depth" message. This seems to be the way to go.

**Comment by sebshader** [comment]
![image](https://user-images.githubusercontent.com/4855965/211232727-a4b355d0-eb7e-4e33-a219-9b83d6e32a08.png)
different help files open here so I think it's working

**Comment by agraef** [comment]
Ok, the name clashes should at least be properly handled with rev. e28dc6dae5050de954bbaf8aeed88c3916c05732 now.

> I believe w/ pd it is possible to load different binaries by path.

Ah ok, that's nice. Unfortunately, I can't make pdlua work that way without redesigning its object class system. I have some ideas how to do this, but this will be a considerable amount of work and need a substantial amount of testing, so this will have to wait for another day. If anyone wants to beat me to it, please go ahead and send me your PR. ;-)

**Comment by sebshader** [comment]
well, it works now but now I can't load a class with multiple different paths. it would be nice if at least that instead of 'class already exists' and just giving an error it could just load the already-loaded class imo

**Comment by agraef** [comment]
> it would be nice if at least that instead of 'class already exists' and just giving an error it could just load the already-loaded class if it exists in the correct location imo

Yes, I understand, but there's no way to do it as far as I can tell. (If you know a way, send me a PR please.)

The proper solution is to overhaul pdlua's object class system so that foo/hello and bar/hello would be different classes, which isn't possible with the way it's currently designed. This is certainly the goal and why I keep this ticket open.

**Comment by sebshader** [comment]
@agraef ok I gave it a shot (I just added a ```_loadname``` field to the pd table when loading a non-basename, then added it to ```pd._classes``` in the register function)

**Comment by agraef** [comment]
Fixed now (for real this time) by @sebshader's PR, thanks!

**Comment by agraef** [comment]
With that it's time for another release, but I'd say I'll give it another day or two so that people can test it and we can shake out any remaining bugs.
