### ISSUE TITLE
ping downstream maintainers rather than ranting about them being out-of-date

### ISSUE THREAD

**Issue by umlaeute** [agraef/pd-lua#34]
it would be fantastic to ping the Debian maintainers (aka: yours sincerely) if you think their packages are out-of-date, rather than [finger-pointing](https://github.com/agraef/pd-lua/blob/master/tutorial/pd-lua-intro.md#installation):

https://github.com/agraef/pd-lua/blob/3dda515e3789f71955389a03661456292ba8d107/tutorial/pd-lua-intro.md?plain=1#L26

sorry, i couldn't really resist :-)

**Comment by umlaeute** [comment]
ah, and i forgot:

> With vanilla Pd, you can install the pdlua package from Deken (not recommended, because at the time of this writing that's a really old version based on Lua 5.1). 

you are of course free to upload an updated version of pdlua to Deken.

**Comment by agraef** [comment]
Johannes, I fail to see any ranting or pointing fingers there on my part, sorry. I'm just discussing the available options, with some (admittedly personal) recommendations. ;-)

And who am I to judge whether Pd users on Debian want or need a new pd-lua package? That's up to you to decide. I understand that some people in the community may actually be using your package with their Lua scripts and may not want to update because there's always the risk that something might break.

For new pd-lua users there's really no reason to stick to the old Lua version, however, and this repo exists to cater for their needs. If this fork gets adopted by you then I welcome that, but I'm not pushing it.

> you are of course free to upload an updated version of pdlua to Deken.

I'm not really into Deken packaging, but fortunately it seems that @porres has already taken care of that.
