### ISSUE TITLE
opening help files for gfx classes searches for `:gfx` suffixed classes

### ISSUE THREAD

**Issue by ben-wes** [agraef/pd-lua#56]
i did a git bisect and found 23ee759e89f68ffacffd703241b0ad490eade40e to be the "bad commit".

when trying to open help files for gfx classes, pdlua will now search for class names with a `:gfx` suffix - like `myobject:gfx-help.pd`

**Comment by ben-wes** [comment]
more precisely, it's obviously this?

https://github.com/agraef/pd-lua/blob/master/pdlua.c#L1224

**Comment by agraef** [comment]
Yes, I needed to introduce the gfx shadow class since non-gui and gui objects need different widget behaviors, and these can only be set at the class level, not for each individual object. Live-coding lets you change a non-gui class to a gui one at a whim, so both classes need to be available for each .pd_lua script, and they can't be named the same.

Well spotted! Bonus points if you find a fix. :) There must be a function or callback somewhere which sets the help patch file name, that needs to be adjusted so that it's the same for both classes.

**Comment by agraef** [comment]
Fixed in rev. d56335e6a06c4048a9dcef822343be90c7e74290.

**Comment by ben-wes** [comment]
oh, nice. thanks for the fix! - looks so simple looking back, but wasn't obvious for me.
